### PR TITLE
Add Elotl logo

### PR DESCRIPTION
**Pull request by myechuri**
Add Elotl logo and entry in index.

### CODE REVIEW

**Comment by keith** [comment]
Thanks! Can you add the DCO (instructions from the status)

**Comment by myechuri** [comment]
Thanks, @keith ! Added DCO.

**Comment by keith** [comment]
Thanks! Added in https://github.com/MobileNativeFoundation/mobilenativefoundation.org/pull/10 after resolving the conflicts!

**Comment by myechuri** [comment]
Thanks, @keith

**Pull request closed without merging**
